sources:
  - name: test
    database: mydatabase
    tables:
      - name: test
        columns:
          - name: id
            data_type: varchar(20)
          - name: name
            data_type: varchar(20)