sources:
  - name: test
    database: mydatabase
    schema: myschema
    tables:
      - name: table1
        columns:
          - name: id
            data_type: varchar(20)
          - name: name
            data_type: varchar(20)
      - name: table2
        columns:
          - name: id
            data_type: varchar(20)
          - name: name
            data_type: varchar(20)
          - name: test_id
            data_type: varchar(20)